projectName: rest-api
apiVersion: v0.0.0
author: TBD.
licence: TBD.
serviceUrlPrefix: /
servicePort: 5001
baseUrl: http://localhost:5001/
servicesRoot: services
services:
    - /mock
    # To add new services, put here the path of the directory that contains the service.yml


loginCredentials:
    user: name
    pass: password
