/**
 * Implementation of method calls defined in `service.yml` files
 * This file is generated by the rest-tool tool.
 */
var services = require('rest-tool-common').services;
var fs = require('fs');

var server = require('./server.js');

//=============================================================================
// Put your mock method implementations here


function writeResult(response, result) {
    response.header('Content-Type', 'application/json');
    response.write(JSON.stringify(result, null, '  '));
    response.end('\n');
}
