## The server config file

# Use this environment by default, if server is started without the --env switch.
useEnvironment: development
#useEnvironment: production

environments:

  # This is the default configuration set
  default:
    documentRoot: ../../angular-seed/app/
    restapiRoot: ..
    useRemoteServices: false

  # Override the default config parameters with values specific to the development environment
  development:
    port: 5002
